name: Laravel CI/CD to DigitalOcean

on:
  push:
    branches:
      - main  # Change this if you use a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to DigitalOcean
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.DO_HOST }}
          REMOTE_USER: ${{ secrets.DO_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ket
          chmod 600 ~/.ssh/id_ket
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "
            cd /var/www/easylink &&
            git pull origin main
          "
